### ISSUE TITLE
Router vs Router input

### ISSUE THREAD

**Issue by kafejo** [thefuntasty/Funtasty-CleanSwift-templates#10]
Members of VIP cycle always have defined output via protocol and therefore are exchangeable with fakers that adopt that protocol (for test purposes). In case of router, there is RouterInput protocol but view controller's router's are declared with the exact name of router class, not the protocol.

``` swift
var output: ___FILEBASENAMEASIDENTIFIER___ViewControllerOutput!
var router: ___FILEBASENAMEASIDENTIFIER___Router!
```

In order to be consistent, it should be defined by the input protocol instead

``` swift
var output: ___FILEBASENAMEASIDENTIFIER___ViewControllerOutput!
var router: ___FILEBASENAMEASIDENTIFIER___RouterInput!
```

There is one problem with this enhancement. I guess this is a workaround of the original author for forwarding `prepareForSegue` method in configurator 

```
extension ___FILEBASENAMEASIDENTIFIER___ViewController {
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        router.passDataToNextScene(segue)
    }
}
```

I think that appropriate enhancement would be to include the `passDataToNextScene` right into these templates to the RouterInput protocol.

What do you think? Or any better solutions?

**Comment by mkj-is** [comment]
I noticed this issue too and I do not see any reason why this should not be updated as proposed. The router input is currently not used, which I believe is a bad choice. And, if this is the case, then the pass data to next scene should be contained in the protocol. Also, the data passing methods are not used in all scenes, so they should be there only when necessary.

**Comment by mkj-is** [comment]
I wanted to merge this pull request, but there isn't one yet. Should I update it or do you want to do this yourself?

**Comment by kafejo** [comment]
I wanted to discuss the issue beforehand. I'll be able to create pull request with solution in a two day's horizon but you can of course do that sooner if you want to.
