### ISSUE TITLE
dont work in

### ISSUE THREAD

**Issue by truextcfans** [thefuntasty/Funtasty-CleanSwift-templates#20]
do not work in xcode9

**Comment by mkj-is** [comment]
Sadly, they do not. We are currently using mainly MVVM so these templates are deprecated for us.

Please send pull request if you want them updated.

**Comment by kafejo** [comment]
@mkj-is would you mind transferring the ownership to me as we continue using and improving these templates internally at @Rubicoin and I would like to open source it. Here or in our own repository.

**Comment by mkj-is** [comment]
Yes, we already discussed this with @zvonicek and we wanted to propose the same thing!

**Comment by mkj-is** [comment]
I cannot transfer the repository to your account since you have forked the repository with the same name. Or should I transfer it to Rubicoin directly?

**Comment by zvonicek** [comment]
Yep, that's what I suggested yesterday. Let's do it.

**Comment by zvonicek** [comment]
@kafejo Send a PR to this repo and we'll merge it, then you can delete your fork and we can proceed with the transfer.

**Comment by kafejo** [comment]
Perfect, I'll prepare it over the following weekend. Thanks!

**Comment by mkj-is** [comment]
@kafejo How does it look?

**Comment by kafejo** [comment]
Sorry, didn't have time for it sooner. #21
